# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Myfirst Azure pipeline for maven project
  displayName: 'Run a one-line script'

- script: mvn clean install
  displayName: 'Build with Maven'
  
- script: java -jar target/MyMavenJenkinsApp-1.0-SNAPSHOT.jar
  displayName: 'Running jar'
